<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Update missing ISO codes for countries
        $updates = [
            ['dialcode' => '290', 'name' => 'St. Helena', 'iso_code' => 'SH'],
            ['dialcode' => '291', 'name' => 'Eritrea', 'iso_code' => 'ER'],
            ['dialcode' => '297', 'name' => 'Aruba', 'iso_code' => 'AW'],
            ['dialcode' => '298', 'name' => 'Faeroe Islands', 'iso_code' => 'FO'],
            ['dialcode' => '299', 'name' => 'Greenland', 'iso_code' => 'GL'],
            ['dialcode' => '30', 'name' => 'Greece', 'iso_code' => 'GR'],
            ['dialcode' => '31', 'name' => 'Netherlands', 'iso_code' => 'NL'],
            ['dialcode' => '32', 'name' => 'Belgium', 'iso_code' => 'BE'],
            ['dialcode' => '33', 'name' => 'France', 'iso_code' => 'FR'],
            ['dialcode' => '34', 'name' => 'Spain', 'iso_code' => 'ES'],
            ['dialcode' => '350', 'name' => 'Gibraltar', 'iso_code' => 'GI'],
            ['dialcode' => '351', 'name' => 'Portugal', 'iso_code' => 'PT'],
            ['dialcode' => '352', 'name' => 'Luxembourg', 'iso_code' => 'LU'],
            ['dialcode' => '353', 'name' => 'Ireland', 'iso_code' => 'IE'],
            ['dialcode' => '354', 'name' => 'Iceland', 'iso_code' => 'IS'],
            ['dialcode' => '355', 'name' => 'Albania', 'iso_code' => 'AL'],
            ['dialcode' => '356', 'name' => 'Malta', 'iso_code' => 'MT'],
            ['dialcode' => '357', 'name' => 'Cyprus', 'iso_code' => 'CY'],
            ['dialcode' => '358', 'name' => 'Finland', 'iso_code' => 'FI'],
            ['dialcode' => '359', 'name' => 'Bulgaria', 'iso_code' => 'BG'],
            ['dialcode' => '36', 'name' => 'Hungary', 'iso_code' => 'HU'],
            ['dialcode' => '370', 'name' => 'Lithuania', 'iso_code' => 'LT'],
            ['dialcode' => '371', 'name' => 'Latvia', 'iso_code' => 'LV'],
            ['dialcode' => '372', 'name' => 'Estonia', 'iso_code' => 'EE'],
            ['dialcode' => '373', 'name' => 'Republic of Moldova', 'iso_code' => 'MD'],
            ['dialcode' => '374', 'name' => 'Armenia', 'iso_code' => 'AM'],
            ['dialcode' => '375', 'name' => 'Belarus', 'iso_code' => 'BY'],
            ['dialcode' => '376', 'name' => 'Andorra', 'iso_code' => 'AD'],
            ['dialcode' => '377', 'name' => 'Monaco', 'iso_code' => 'MC'],
            ['dialcode' => '378', 'name' => 'San Marino', 'iso_code' => 'SM'],
            ['dialcode' => '380', 'name' => 'Ukraine', 'iso_code' => 'UA'],
            ['dialcode' => '381', 'name' => 'Serbia', 'iso_code' => 'RS'],
            ['dialcode' => '385', 'name' => 'Croatia', 'iso_code' => 'HR'],
            ['dialcode' => '386', 'name' => 'Slovenia', 'iso_code' => 'SI'],
            ['dialcode' => '387', 'name' => 'Bosnia - Herzegovina', 'iso_code' => 'BA'],
            ['dialcode' => '389', 'name' => 'Macedonia', 'iso_code' => 'MK'],
            ['dialcode' => '39', 'name' => 'Italy', 'iso_code' => 'IT'],
            ['dialcode' => '39', 'name' => 'Vatican City', 'iso_code' => 'VA'],
            ['dialcode' => '40', 'name' => 'Romania', 'iso_code' => 'RO'],
            ['dialcode' => '41', 'name' => 'Switzerland', 'iso_code' => 'CH'],
            ['dialcode' => '420', 'name' => 'Czech Republic', 'iso_code' => 'CZ'],
            ['dialcode' => '421', 'name' => 'Slovakia', 'iso_code' => 'SK'],
            ['dialcode' => '423', 'name' => 'Liechtenstein', 'iso_code' => 'LI'],
            ['dialcode' => '43', 'name' => 'Austria', 'iso_code' => 'AT'],
            ['dialcode' => '44', 'name' => 'United Kingdom', 'iso_code' => 'GB'],
            ['dialcode' => '45', 'name' => 'Denmark', 'iso_code' => 'DK'],
            ['dialcode' => '46', 'name' => 'Sweden', 'iso_code' => 'SE'],
            ['dialcode' => '47', 'name' => 'Norway', 'iso_code' => 'NO'],
            ['dialcode' => '48', 'name' => 'Poland', 'iso_code' => 'PL'],
            ['dialcode' => '49', 'name' => 'Germany', 'iso_code' => 'DE'],
            ['dialcode' => '500', 'name' => 'Falkland Islands (Malvinas)', 'iso_code' => 'FK'],
            ['dialcode' => '501', 'name' => 'Belize', 'iso_code' => 'BZ'],
            ['dialcode' => '502', 'name' => 'Guatemala', 'iso_code' => 'GT'],
            ['dialcode' => '503', 'name' => 'El Salvador', 'iso_code' => 'SV'],
            ['dialcode' => '504', 'name' => 'Honduras', 'iso_code' => 'HN'],
            ['dialcode' => '505', 'name' => 'Nicaragua', 'iso_code' => 'NI'],
            ['dialcode' => '506', 'name' => 'Costa Rica', 'iso_code' => 'CR'],
            ['dialcode' => '507', 'name' => 'Panama', 'iso_code' => 'PA'],
            ['dialcode' => '508', 'name' => 'St Pierre and Miquelon', 'iso_code' => 'PM'],
            ['dialcode' => '509', 'name' => 'Haiti', 'iso_code' => 'HT'],
            ['dialcode' => '51', 'name' => 'Peru', 'iso_code' => 'PE'],
            ['dialcode' => '52', 'name' => 'Mexico', 'iso_code' => 'MX'],
            ['dialcode' => '53', 'name' => 'Cuba', 'iso_code' => 'CU'],
            ['dialcode' => '54', 'name' => 'Argentina', 'iso_code' => 'AR'],
            ['dialcode' => '55', 'name' => 'Brazil', 'iso_code' => 'BR'],
            ['dialcode' => '56', 'name' => 'Chile', 'iso_code' => 'CL'],
            ['dialcode' => '57', 'name' => 'Colombia', 'iso_code' => 'CO'],
            ['dialcode' => '590', 'name' => 'Guadeloupe', 'iso_code' => 'GP'],
            ['dialcode' => '591', 'name' => 'Bolivia', 'iso_code' => 'BO'],
            ['dialcode' => '592', 'name' => 'Guyana', 'iso_code' => 'GY'],
            ['dialcode' => '593', 'name' => 'Ecuador', 'iso_code' => 'EC'],
            ['dialcode' => '594', 'name' => 'French Guiana', 'iso_code' => 'GF'],
            ['dialcode' => '595', 'name' => 'Paraguay', 'iso_code' => 'PY'],
            ['dialcode' => '596', 'name' => 'Martinique', 'iso_code' => 'MQ'],
            ['dialcode' => '597', 'name' => 'Surinam', 'iso_code' => 'SR'],
            ['dialcode' => '598', 'name' => 'Uruguay', 'iso_code' => 'UY'],
            ['dialcode' => '599', 'name' => 'Netherlands Antilles', 'iso_code' => 'AN'],
            ['dialcode' => '60', 'name' => 'Malaysia', 'iso_code' => 'MY'],
            ['dialcode' => '61', 'name' => 'Australia', 'iso_code' => 'AU'],
            ['dialcode' => '61', 'name' => 'Christmas Island', 'iso_code' => 'CX'],
            ['dialcode' => '61', 'name' => 'Cocos Island', 'iso_code' => 'CC'],
            ['dialcode' => '62', 'name' => 'Indonesia', 'iso_code' => 'ID'],
            ['dialcode' => '63', 'name' => 'Philippines', 'iso_code' => 'PH'],
            ['dialcode' => '64', 'name' => 'New Zealand', 'iso_code' => 'NZ'],
            ['dialcode' => '65', 'name' => 'Singapore', 'iso_code' => 'SG'],
            ['dialcode' => '66', 'name' => 'Thailand', 'iso_code' => 'TH'],
            ['dialcode' => '672', 'name' => 'Antarctic Australian Territory', 'iso_code' => 'AQ'],
            ['dialcode' => '672', 'name' => 'Norfolk Island', 'iso_code' => 'NF'],
            ['dialcode' => '673', 'name' => 'Brunei', 'iso_code' => 'BN'],
            ['dialcode' => '674', 'name' => 'Nauru', 'iso_code' => 'NR'],
            ['dialcode' => '675', 'name' => 'Papua New Guinea', 'iso_code' => 'PG'],
            ['dialcode' => '677', 'name' => 'Solomon Islands', 'iso_code' => 'SB'],
            ['dialcode' => '678', 'name' => 'Vanuatu', 'iso_code' => 'VU'],
            ['dialcode' => '679', 'name' => 'Fiji', 'iso_code' => 'FJ'],
            ['dialcode' => '680', 'name' => 'Palau', 'iso_code' => 'PW'],
            ['dialcode' => '682', 'name' => 'Cook Islands', 'iso_code' => 'CK'],
            ['dialcode' => '683', 'name' => 'Niue', 'iso_code' => 'NU'],
            ['dialcode' => '684', 'name' => 'Samoa', 'iso_code' => 'AS'],
            ['dialcode' => '685', 'name' => 'Western Samoa', 'iso_code' => 'WS'],
            ['dialcode' => '686', 'name' => 'Kiribati', 'iso_code' => 'KI'],
            ['dialcode' => '687', 'name' => 'New Caledonia', 'iso_code' => 'NC'],
            ['dialcode' => '688', 'name' => 'Tuvalu', 'iso_code' => 'TV'],
            ['dialcode' => '689', 'name' => 'French Polynesia', 'iso_code' => 'PF'],
            ['dialcode' => '691', 'name' => 'Micronesia', 'iso_code' => 'FM'],
            ['dialcode' => '692', 'name' => 'Marshall Islands', 'iso_code' => 'MH'],
            ['dialcode' => '7', 'name' => 'Kazakhstan', 'iso_code' => 'KZ'],
            ['dialcode' => '7', 'name' => 'Russian Federation', 'iso_code' => 'RU'],
            ['dialcode' => '7', 'name' => 'Tajikistan', 'iso_code' => 'TJ'],
            ['dialcode' => '7', 'name' => 'Uzbekistan', 'iso_code' => 'UZ'],
            ['dialcode' => '81', 'name' => 'Japan', 'iso_code' => 'JP'],
            ['dialcode' => '82', 'name' => 'South Korea', 'iso_code' => 'KR'],
            ['dialcode' => '84', 'name' => 'Vietnam', 'iso_code' => 'VN'],
            ['dialcode' => '850', 'name' => 'North Korea', 'iso_code' => 'KP'],
            ['dialcode' => '852', 'name' => 'Hong Kong', 'iso_code' => 'HK'],
            ['dialcode' => '853', 'name' => 'Macau', 'iso_code' => 'MO'],
            ['dialcode' => '855', 'name' => 'Cambodia', 'iso_code' => 'KH'],
            ['dialcode' => '856', 'name' => 'Laos', 'iso_code' => 'LA'],
            ['dialcode' => '86', 'name' => 'China', 'iso_code' => 'CN'],
            ['dialcode' => '880', 'name' => 'Bangladesh', 'iso_code' => 'BD'],
            ['dialcode' => '886', 'name' => 'Taiwan', 'iso_code' => 'TW'],
            ['dialcode' => '90', 'name' => 'Turkey', 'iso_code' => 'TR'],
            ['dialcode' => '91', 'name' => 'India', 'iso_code' => 'IN'],
            ['dialcode' => '92', 'name' => 'Pakistan', 'iso_code' => 'PK'],
            ['dialcode' => '93', 'name' => 'Afghanistan', 'iso_code' => 'AF'],
            ['dialcode' => '94', 'name' => 'Sri Lanka', 'iso_code' => 'LK'],
            ['dialcode' => '95', 'name' => 'Myanmar', 'iso_code' => 'MM'],
            ['dialcode' => '95', 'name' => 'Myanmar (Formerly Burma)', 'iso_code' => 'MM'],
            ['dialcode' => '960', 'name' => 'Maldives', 'iso_code' => 'MV'],
            ['dialcode' => '961', 'name' => 'Lebanon', 'iso_code' => 'LB'],
            ['dialcode' => '962', 'name' => 'Jordan', 'iso_code' => 'JO'],
            ['dialcode' => '963', 'name' => 'Syria', 'iso_code' => 'SY'],
            ['dialcode' => '964', 'name' => 'Iraq', 'iso_code' => 'IQ'],
            ['dialcode' => '966', 'name' => 'Saudi Arabia', 'iso_code' => 'SA'],
            ['dialcode' => '967', 'name' => 'Yemen', 'iso_code' => 'YE'],
            ['dialcode' => '968', 'name' => 'Oman', 'iso_code' => 'OM'],
            ['dialcode' => '971', 'name' => 'United Arab Emirates', 'iso_code' => 'AE'],
            ['dialcode' => '972', 'name' => 'Israel', 'iso_code' => 'IL'],
            ['dialcode' => '973', 'name' => 'Bahrain', 'iso_code' => 'BH'],
            ['dialcode' => '974', 'name' => 'Qatar', 'iso_code' => 'QA'],
            ['dialcode' => '975', 'name' => 'Bhutan', 'iso_code' => 'BT'],
            ['dialcode' => '976', 'name' => 'Mongolia', 'iso_code' => 'MN'],
            ['dialcode' => '977', 'name' => 'Nepal', 'iso_code' => 'NP'],
            ['dialcode' => '98', 'name' => 'Iran', 'iso_code' => 'IR'],
            ['dialcode' => '993', 'name' => 'Turkmenistan', 'iso_code' => 'TM'],
            ['dialcode' => '994', 'name' => 'Azerbaijan', 'iso_code' => 'AZ'],
            ['dialcode' => '995', 'name' => 'Georgia', 'iso_code' => 'GE'],
            ['dialcode' => '996', 'name' => 'Kyrgyzstan', 'iso_code' => 'KG'],
        ];

        foreach ($updates as $update) {
            DB::table('country')
                ->where('dialcode', $update['dialcode'])
                ->where('name', $update['name'])
                ->whereNull('iso_code')
                ->update(['iso_code' => $update['iso_code']]);
        }

        // Note: Roaming SIM doesn't have a standard ISO code
        // You can add a custom code if needed
        // DB::table('country')
        //     ->where('dialcode', '882')
        //     ->where('name', 'Roaming SIM')
        //     ->update(['iso_code' => 'XX']); // Custom code
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Set all the ISO codes back to NULL for countries that were updated
        $countries = [
            ['dialcode' => '290', 'name' => 'St. Helena'],
            ['dialcode' => '291', 'name' => 'Eritrea'],
            ['dialcode' => '297', 'name' => 'Aruba'],
            ['dialcode' => '298', 'name' => 'Faeroe Islands'],
            ['dialcode' => '299', 'name' => 'Greenland'],
            ['dialcode' => '30', 'name' => 'Greece'],
            ['dialcode' => '31', 'name' => 'Netherlands'],
            ['dialcode' => '32', 'name' => 'Belgium'],
            ['dialcode' => '33', 'name' => 'France'],
            ['dialcode' => '34', 'name' => 'Spain'],
            ['dialcode' => '350', 'name' => 'Gibraltar'],
            ['dialcode' => '351', 'name' => 'Portugal'],
            ['dialcode' => '352', 'name' => 'Luxembourg'],
            ['dialcode' => '353', 'name' => 'Ireland'],
            ['dialcode' => '354', 'name' => 'Iceland'],
            ['dialcode' => '355', 'name' => 'Albania'],
            ['dialcode' => '356', 'name' => 'Malta'],
            ['dialcode' => '357', 'name' => 'Cyprus'],
            ['dialcode' => '358', 'name' => 'Finland'],
            ['dialcode' => '359', 'name' => 'Bulgaria'],
            ['dialcode' => '36', 'name' => 'Hungary'],
            ['dialcode' => '370', 'name' => 'Lithuania'],
            ['dialcode' => '371', 'name' => 'Latvia'],
            ['dialcode' => '372', 'name' => 'Estonia'],
            ['dialcode' => '373', 'name' => 'Republic of Moldova'],
            ['dialcode' => '374', 'name' => 'Armenia'],
            ['dialcode' => '375', 'name' => 'Belarus'],
            ['dialcode' => '376', 'name' => 'Andorra'],
            ['dialcode' => '377', 'name' => 'Monaco'],
            ['dialcode' => '378', 'name' => 'San Marino'],
            ['dialcode' => '380', 'name' => 'Ukraine'],
            ['dialcode' => '381', 'name' => 'Serbia'],
            ['dialcode' => '385', 'name' => 'Croatia'],
            ['dialcode' => '386', 'name' => 'Slovenia'],
            ['dialcode' => '387', 'name' => 'Bosnia - Herzegovina'],
            ['dialcode' => '389', 'name' => 'Macedonia'],
            ['dialcode' => '39', 'name' => 'Italy'],
            ['dialcode' => '39', 'name' => 'Vatican City'],
            ['dialcode' => '40', 'name' => 'Romania'],
            ['dialcode' => '41', 'name' => 'Switzerland'],
            ['dialcode' => '420', 'name' => 'Czech Republic'],
            ['dialcode' => '421', 'name' => 'Slovakia'],
            ['dialcode' => '423', 'name' => 'Liechtenstein'],
            ['dialcode' => '43', 'name' => 'Austria'],
            ['dialcode' => '44', 'name' => 'United Kingdom'],
            ['dialcode' => '45', 'name' => 'Denmark'],
            ['dialcode' => '46', 'name' => 'Sweden'],
            ['dialcode' => '47', 'name' => 'Norway'],
            ['dialcode' => '48', 'name' => 'Poland'],
            ['dialcode' => '49', 'name' => 'Germany'],
            ['dialcode' => '500', 'name' => 'Falkland Islands (Malvinas)'],
            ['dialcode' => '501', 'name' => 'Belize'],
            ['dialcode' => '502', 'name' => 'Guatemala'],
            ['dialcode' => '503', 'name' => 'El Salvador'],
            ['dialcode' => '504', 'name' => 'Honduras'],
            ['dialcode' => '505', 'name' => 'Nicaragua'],
            ['dialcode' => '506', 'name' => 'Costa Rica'],
            ['dialcode' => '507', 'name' => 'Panama'],
            ['dialcode' => '508', 'name' => 'St Pierre and Miquelon'],
            ['dialcode' => '509', 'name' => 'Haiti'],
            ['dialcode' => '51', 'name' => 'Peru'],
            ['dialcode' => '52', 'name' => 'Mexico'],
            ['dialcode' => '53', 'name' => 'Cuba'],
            ['dialcode' => '54', 'name' => 'Argentina'],
            ['dialcode' => '55', 'name' => 'Brazil'],
            ['dialcode' => '56', 'name' => 'Chile'],
            ['dialcode' => '57', 'name' => 'Colombia'],
            ['dialcode' => '590', 'name' => 'Guadeloupe'],
            ['dialcode' => '591', 'name' => 'Bolivia'],
            ['dialcode' => '592', 'name' => 'Guyana'],
            ['dialcode' => '593', 'name' => 'Ecuador'],
            ['dialcode' => '594', 'name' => 'French Guiana'],
            ['dialcode' => '595', 'name' => 'Paraguay'],
            ['dialcode' => '596', 'name' => 'Martinique'],
            ['dialcode' => '597', 'name' => 'Surinam'],
            ['dialcode' => '598', 'name' => 'Uruguay'],
            ['dialcode' => '599', 'name' => 'Netherlands Antilles'],
            ['dialcode' => '60', 'name' => 'Malaysia'],
            ['dialcode' => '61', 'name' => 'Australia'],
            ['dialcode' => '61', 'name' => 'Christmas Island'],
            ['dialcode' => '61', 'name' => 'Cocos Island'],
            ['dialcode' => '62', 'name' => 'Indonesia'],
            ['dialcode' => '63', 'name' => 'Philippines'],
            ['dialcode' => '64', 'name' => 'New Zealand'],
            ['dialcode' => '65', 'name' => 'Singapore'],
            ['dialcode' => '66', 'name' => 'Thailand'],
            ['dialcode' => '672', 'name' => 'Antarctic Australian Territory'],
            ['dialcode' => '672', 'name' => 'Norfolk Island'],
            ['dialcode' => '673', 'name' => 'Brunei'],
            ['dialcode' => '674', 'name' => 'Nauru'],
            ['dialcode' => '675', 'name' => 'Papua New Guinea'],
            ['dialcode' => '677', 'name' => 'Solomon Islands'],
            ['dialcode' => '678', 'name' => 'Vanuatu'],
            ['dialcode' => '679', 'name' => 'Fiji'],
            ['dialcode' => '680', 'name' => 'Palau'],
            ['dialcode' => '682', 'name' => 'Cook Islands'],
            ['dialcode' => '683', 'name' => 'Niue'],
            ['dialcode' => '684', 'name' => 'Samoa'],
            ['dialcode' => '685', 'name' => 'Western Samoa'],
            ['dialcode' => '686', 'name' => 'Kiribati'],
            ['dialcode' => '687', 'name' => 'New Caledonia'],
            ['dialcode' => '688', 'name' => 'Tuvalu'],
            ['dialcode' => '689', 'name' => 'French Polynesia'],
            ['dialcode' => '691', 'name' => 'Micronesia'],
            ['dialcode' => '692', 'name' => 'Marshall Islands'],
            ['dialcode' => '7', 'name' => 'Kazakhstan'],
            ['dialcode' => '7', 'name' => 'Russian Federation'],
            ['dialcode' => '7', 'name' => 'Tajikistan'],
            ['dialcode' => '7', 'name' => 'Uzbekistan'],
            ['dialcode' => '81', 'name' => 'Japan'],
            ['dialcode' => '82', 'name' => 'South Korea'],
            ['dialcode' => '84', 'name' => 'Vietnam'],
            ['dialcode' => '850', 'name' => 'North Korea'],
            ['dialcode' => '852', 'name' => 'Hong Kong'],
            ['dialcode' => '853', 'name' => 'Macau'],
            ['dialcode' => '855', 'name' => 'Cambodia'],
            ['dialcode' => '856', 'name' => 'Laos'],
            ['dialcode' => '86', 'name' => 'China'],
            ['dialcode' => '880', 'name' => 'Bangladesh'],
            ['dialcode' => '886', 'name' => 'Taiwan'],
            ['dialcode' => '90', 'name' => 'Turkey'],
            ['dialcode' => '91', 'name' => 'India'],
            ['dialcode' => '92', 'name' => 'Pakistan'],
            ['dialcode' => '93', 'name' => 'Afghanistan'],
            ['dialcode' => '94', 'name' => 'Sri Lanka'],
            ['dialcode' => '95', 'name' => 'Myanmar'],
            ['dialcode' => '95', 'name' => 'Myanmar (Formerly Burma)'],
            ['dialcode' => '960', 'name' => 'Maldives'],
            ['dialcode' => '961', 'name' => 'Lebanon'],
            ['dialcode' => '962', 'name' => 'Jordan'],
            ['dialcode' => '963', 'name' => 'Syria'],
            ['dialcode' => '964', 'name' => 'Iraq'],
            ['dialcode' => '966', 'name' => 'Saudi Arabia'],
            ['dialcode' => '967', 'name' => 'Yemen'],
            ['dialcode' => '968', 'name' => 'Oman'],
            ['dialcode' => '971', 'name' => 'United Arab Emirates'],
            ['dialcode' => '972', 'name' => 'Israel'],
            ['dialcode' => '973', 'name' => 'Bahrain'],
            ['dialcode' => '974', 'name' => 'Qatar'],
            ['dialcode' => '975', 'name' => 'Bhutan'],
            ['dialcode' => '976', 'name' => 'Mongolia'],
            ['dialcode' => '977', 'name' => 'Nepal'],
            ['dialcode' => '98', 'name' => 'Iran'],
            ['dialcode' => '993', 'name' => 'Turkmenistan'],
            ['dialcode' => '994', 'name' => 'Azerbaijan'],
            ['dialcode' => '995', 'name' => 'Georgia'],
            ['dialcode' => '996', 'name' => 'Kyrgyzstan'],
        ];

        foreach ($countries as $country) {
            DB::table('country')
                ->where('dialcode', $country['dialcode'])
                ->where('name', $country['name'])
                ->update(['iso_code' => null]);
        }
    }
};