[program:email-queue-consumer]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/sms_expert_new-BE/artisan rabbitmq:consume-emails --timeout=60
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/sms_expert_new-BE/storage/logs/email-consumer.log
stopwaitsecs=3600
stopsignal=SIGTERM
